(() => {
  'use strict';
  const cfg = window.RoomFlowTrackerConfig || {};
  const client = window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey);
  const s = { user:null, orgs:[], orgId:localStorage.getItem('roomflow_tracker_org')||'', jobs:[], equipment:[], deployments:[], channels:[], boardPage:0, boardPages:1, boardPaused:false, boardTimer:null };
  const $ = id => document.getElementById(id);
  const esc = v => String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const fmtDate = v => v ? new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}) : 'Not scheduled';
  const toast = (m,t='success') => { const e=$('toast');e.textContent=m;e.className=`toast ${t}`;setTimeout(()=>e.classList.add('hidden'),4200); };
  const statuses=['New Lead','Contacted','Inspection Scheduled','Inspection Complete','Layout In Progress','Estimate Draft','Estimate Ready','Estimate Sent','Customer Replied','Approved','Declined','Work Scheduled','In Progress','Completed','Invoiced','Paid','Service Not Needed','Call Back','Emergency'];

  async function boot(){
    const {data:{session}}=await client.auth.getSession();
    if(session) await enter(session.user); else $('auth-overlay').classList.remove('hidden');
    client.auth.onAuthStateChange((_event,session)=>{ if(session?.user&&!s.user) enter(session.user); });
  }
  async function enter(user){s.user=user;$('auth-overlay').classList.add('hidden');$('app').classList.remove('hidden');await loadOrganizations();}
  async function loadOrganizations(){
    const {data:members,error}=await client.from('organization_members').select('organization_id').eq('user_id',s.user.id);
    if(error)return toast(error.message,'error');
    const ids=(members||[]).map(x=>x.organization_id);
    const {data:orgs}=ids.length?await client.from('organizations').select('id,name').in('id',ids):{data:[]};
    s.orgs=orgs||[]; if(!s.orgs.some(o=>o.id===s.orgId))s.orgId=s.orgs[0]?.id||'';
    $('organization-select').innerHTML=s.orgs.map(o=>`<option value="${o.id}" ${o.id===s.orgId?'selected':''}>${esc(o.name)}</option>`).join('')||'<option>No companies</option>';
    if(s.orgId){localStorage.setItem('roomflow_tracker_org',s.orgId);await refreshAll();subscribe();}
  }
  async function refreshAll(){ $('connection-status').textContent='Syncing…'; await Promise.all([loadJobs(),loadEquipment(),loadDeployments()]); $('connection-status').textContent=`Live · ${new Date().toLocaleTimeString()}`; }
  async function loadJobs(){
    const {data,error}=await client.from('jobs').select('id,name,status,property_address,city,state,postal_code,issue_description,appointment_start,estimate_status,tracking_color,updated_at,customer_id,customers(id,name,email,phone,address,city,state,postal_code)').eq('organization_id',s.orgId).order('updated_at',{ascending:false}).limit(300);
    if(error)return toast(error.message,'error');s.jobs=data||[];renderJobs();
  }
  function boardLayout(){
    const board=$('jobs-board'), width=Math.max(280,board?.clientWidth||window.innerWidth-24);
    const columns=Math.max(1,Math.min(8,Math.floor(width/250)));
    const top=board?.getBoundingClientRect().top||300;
    const available=Math.max(170,window.innerHeight-top-58);
    const rows=Math.max(1,Math.floor(available/172));
    board?.style.setProperty('--board-columns',columns);
    return {columns,rows,pageSize:columns*rows};
  }
  function statusColor(job){
    const named={red:'#ef4444',green:'#10b981',blue:'#3b82f6',yellow:'#f59e0b',purple:'#a855f7',gray:'#64748b'};
    if(named[job.tracking_color])return named[job.tracking_color];
    return {Emergency:'#ef4444',Declined:'#ef4444',Approved:'#10b981',Completed:'#10b981','Estimate Sent':'#22c55e','In Progress':'#3b82f6','New Lead':'#f59e0b'}[job.status]||'#64748b';
  }
  function scheduleBoardRotation(){
    clearInterval(s.boardTimer);s.boardTimer=null;
    const jobsActive=$('jobs-tab')?.classList.contains('active');
    if(!s.boardPaused&&s.boardPages>1&&jobsActive&&!document.hidden){s.boardTimer=setInterval(()=>showBoardPage(s.boardPage+1),12000);}
  }
  function showBoardPage(page){s.boardPage=(page+s.boardPages)%s.boardPages;renderJobs();}
  function renderJobs(resetPage=false){
    const q=($('job-search').value||'').toLowerCase(), filter=$('job-status-filter').value;
    const rows=s.jobs.filter(j=>{const c=Array.isArray(j.customers)?j.customers[0]:j.customers;return(!filter||j.status===filter)&&(!q||`${j.name} ${c?.name||''} ${c?.phone||''} ${c?.email||''} ${j.property_address||''} ${j.city||''}`.toLowerCase().includes(q));});
    const counts={};s.jobs.forEach(j=>counts[j.status]=(counts[j.status]||0)+1);
    $('job-metrics').innerHTML=[['All Jobs',s.jobs.length],['New Leads',counts['New Lead']||0],['Estimates Sent',counts['Estimate Sent']||0],['Approved',counts.Approved||0],['In Progress',counts['In Progress']||0],['Completed',counts.Completed||0]].map(([k,v])=>`<div class="metric"><strong>${v}</strong><span>${k}</span></div>`).join('');
    const {pageSize}=boardLayout();s.boardPages=Math.max(1,Math.ceil(rows.length/pageSize));
    if(resetPage)s.boardPage=0;s.boardPage=Math.min(s.boardPage,s.boardPages-1);
    const visible=rows.slice(s.boardPage*pageSize,(s.boardPage+1)*pageSize);
    $('jobs-board').innerHTML=visible.map(j=>{const c=Array.isArray(j.customers)?j.customers[0]:j.customers;const address=[j.property_address||c?.address,j.city||c?.city,j.state||c?.state,j.postal_code||c?.postal_code].filter(Boolean).join(', ');const contact=[c?.phone,c?.email].filter(Boolean).join(' · ');return`<article class="job-card" style="--status-color:${statusColor(j)}"><div class="job-card-head"><h3 title="${esc(c?.name||j.name)}">${esc(c?.name||j.name)}</h3><select class="status-select" data-job-status="${j.id}" aria-label="Status for ${esc(c?.name||j.name)}">${statuses.map(x=>`<option ${x===j.status?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="job-detail" title="${esc(address)}">⌖ <span>${esc(address||'No address')}</span></div><div class="job-detail" title="${esc(contact)}">☎ <span>${esc(contact||'No contact details')}</span></div><div class="job-issue" title="${esc(j.issue_description||'')}">${esc(j.issue_description||'No issue details')}</div><div class="job-card-foot"><div><div class="job-detail"><strong>${esc(fmtDate(j.appointment_start))}</strong></div><span class="estimate-badge">${esc(j.estimate_status||'not started')}</span></div><button class="secondary card-edit" data-edit-job="${j.id}">Edit</button></div></article>`}).join('')||'<div class="empty-board">No jobs match the current filters.</div>';
    $('board-page-label').textContent=`Page ${s.boardPage+1} of ${s.boardPages} · ${rows.length} jobs · ${pageSize} per screen`;
    $('board-dots').innerHTML=Array.from({length:s.boardPages},(_,i)=>`<button class="board-dot ${i===s.boardPage?'active':''}" data-board-page="${i}" aria-label="Show page ${i+1}"></button>`).join('');
    $('board-carousel').classList.toggle('single-page',s.boardPages<2);
    document.querySelectorAll('[data-board-page]').forEach(el=>el.onclick=()=>showBoardPage(Number(el.dataset.boardPage)));
    document.querySelectorAll('[data-job-status]').forEach(el=>el.onchange=()=>changeStatus(el.dataset.jobStatus,el.value));
    document.querySelectorAll('[data-edit-job]').forEach(el=>el.onclick=()=>openJobModal(el.dataset.editJob));
    scheduleBoardRotation();
  }
  async function changeStatus(id,newStatus){const job=s.jobs.find(x=>x.id===id);const color={Approved:'green',Declined:'red','In Progress':'blue',Emergency:'red','Estimate Sent':'green','New Lead':'yellow'}[newStatus]||'gray';const {error}=await client.from('jobs').update({status:newStatus,tracking_color:color}).eq('id',id);if(error)return toast(error.message,'error');await client.from('job_status_events').insert({organization_id:s.orgId,job_id:id,event_type:'status.changed',old_status:job?.status,new_status:newStatus,actor_user_id:s.user.id});toast('Job status updated.');loadJobs();}
  function openModal(title,html,onSubmit){clearInterval(s.boardTimer);$('modal-title').textContent=title;$('modal-form').innerHTML=html;$('modal').classList.remove('hidden');$('modal-form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));};}
  function closeModal(){$('modal').classList.add('hidden');scheduleBoardRotation();}
  function openJobModal(id){const j=s.jobs.find(x=>x.id===id);const c=Array.isArray(j?.customers)?j.customers[0]:j?.customers;openModal(j?'Edit Job':'Add Job',`<label>Customer Name<input name="name" required value="${esc(c?.name||'')}"></label><label>Phone<input name="phone" value="${esc(c?.phone||'')}"></label><label>Email<input name="email" type="email" value="${esc(c?.email||'')}"></label><label>Appointment<input name="appointment" type="datetime-local" value="${j?.appointment_start?new Date(j.appointment_start).toISOString().slice(0,16):''}"></label><label class="full">Property Address<input name="address" value="${esc(j?.property_address||c?.address||'')}"></label><label>City<input name="city" value="${esc(j?.city||c?.city||'')}"></label><label>State<input name="state" value="${esc(j?.state||c?.state||'MI')}"></label><label>ZIP<input name="zip" value="${esc(j?.postal_code||c?.postal_code||'')}"></label><label>Status<select name="status">${statuses.map(x=>`<option ${x===j?.status?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Issue / Notes<textarea name="issue">${esc(j?.issue_description||'')}</textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancel-modal">Cancel</button><button class="primary">Save</button></div>`,fd=>saveJob(id,fd));setTimeout(()=>$('cancel-modal').onclick=closeModal);}
  async function saveJob(id,fd){
    const values=Object.fromEntries(fd.entries());let customerId=s.jobs.find(x=>x.id===id)?.customer_id||null;
    const customer={organization_id:s.orgId,name:values.name,phone:values.phone||null,email:values.email||null,address:values.address||null,city:values.city||null,state:values.state||null,postal_code:values.zip||null};
    if(customerId){const r=await client.from('customers').update(customer).eq('id',customerId);if(r.error)return toast(r.error.message,'error');}
    else{const r=await client.from('customers').insert(customer).select('id').single();if(r.error)return toast(r.error.message,'error');customerId=r.data.id;}
    const job={organization_id:s.orgId,customer_id:customerId,name:`${values.name}${values.address?' - '+values.address:''}`,status:values.status,property_address:values.address||null,city:values.city||null,state:values.state||null,postal_code:values.zip||null,issue_description:values.issue||null,appointment_start:values.appointment?new Date(values.appointment).toISOString():null};
    const r=id?await client.from('jobs').update(job).eq('id',id):await client.from('jobs').insert(job);if(r.error)return toast(r.error.message,'error');closeModal();toast('Job saved.');loadJobs();
  }
  async function loadEquipment(){const {data,error}=await client.from('equipment_types').select('*').eq('organization_id',s.orgId).order('name');if(error)return toast(error.message,'error');s.equipment=data||[];renderEquipment();}
  async function loadDeployments(){const {data,error}=await client.from('equipment_deployments').select('*,jobs(name),equipment_deployment_items(id,quantity,equipment_type_id,equipment_types(name))').eq('organization_id',s.orgId).order('dropped_off_at',{ascending:false});if(error)return toast(error.message,'error');s.deployments=data||[];renderEquipment();renderDeployments();}
  function deployedCount(typeId){return s.deployments.filter(d=>d.status==='active').flatMap(d=>d.equipment_deployment_items||[]).filter(i=>i.equipment_type_id===typeId).reduce((n,i)=>n+Number(i.quantity||0),0);}
  function renderEquipment(){$('equipment-grid').innerHTML=s.equipment.map(e=>{const dep=deployedCount(e.id),avail=Math.max(0,e.total_owned-dep);return`<article class="equipment-card"><h3>${esc(e.name)}</h3><div class="equipment-numbers"><div><strong>${e.total_owned}</strong><span>Owned</span></div><div><strong>${dep}</strong><span>Deployed</span></div><div><strong>${avail}</strong><span>Available</span></div></div><div class="card-actions"><button class="secondary" data-edit-equip="${e.id}">Edit</button></div></article>`}).join('')||'<div>No equipment types yet.</div>';document.querySelectorAll('[data-edit-equip]').forEach(b=>b.onclick=()=>openEquipmentModal(b.dataset.editEquip));}
  function openEquipmentModal(id){const e=s.equipment.find(x=>x.id===id);openModal(e?'Edit Equipment':'Add Equipment',`<label class="full">Name<input name="name" required value="${esc(e?.name||'')}"></label><label>Total Owned<input name="total" type="number" min="0" required value="${e?.total_owned||0}"></label><label>Active<select name="active"><option value="true" ${e?.active!==false?'selected':''}>Yes</option><option value="false" ${e?.active===false?'selected':''}>No</option></select></label><label class="full">Notes<textarea name="notes">${esc(e?.notes||'')}</textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancel-modal">Cancel</button><button class="primary">Save</button></div>`,async fd=>{const v=Object.fromEntries(fd.entries()),payload={organization_id:s.orgId,name:v.name,total_owned:Number(v.total)||0,active:v.active==='true',notes:v.notes||null};const r=id?await client.from('equipment_types').update(payload).eq('id',id):await client.from('equipment_types').insert(payload);if(r.error)return toast(r.error.message,'error');closeModal();toast('Equipment saved.');loadEquipment();});setTimeout(()=>$('cancel-modal').onclick=closeModal);}
  function renderDeployments(){$('deployments-grid').innerHTML=s.deployments.map(d=>`<article class="deployment-card"><h3>${esc(d.customer_name||d.jobs?.name||'Drop-off')}</h3><div class="sub">${esc(d.location||'No location')}</div><p>${(d.equipment_deployment_items||[]).map(i=>`${esc(i.equipment_types?.name||'Equipment')}: ${i.quantity}`).join('<br>')||'No equipment items'}</p><div class="sub">Dropped off ${fmtDate(d.dropped_off_at)} · ${esc(d.status)}</div>${d.status==='active'?`<div class="card-actions"><button class="primary" data-close-deploy="${d.id}">Mark Picked Up</button></div>`:''}</article>`).join('')||'<div>No equipment deployments yet.</div>';document.querySelectorAll('[data-close-deploy]').forEach(b=>b.onclick=()=>closeDeployment(b.dataset.closeDeploy));}
  function openDeploymentModal(){const jobOpts=s.jobs.map(j=>`<option value="${j.id}">${esc(j.name)}</option>`).join(''),eqRows=s.equipment.map(e=>`<label>${esc(e.name)}<input name="eq_${e.id}" type="number" min="0" max="${Math.max(0,e.total_owned-deployedCount(e.id))}" value="0"></label>`).join('');openModal('New Equipment Drop-off',`<label class="full">Job<select name="job_id" required><option value="">Select job…</option>${jobOpts}</select></label><label>Customer / Site Name<input name="customer_name"></label><label>Pickup Due<input name="pickup_due" type="datetime-local"></label><label class="full">Location<input name="location"></label><div class="full" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px"><h3 style="grid-column:1/-1">Equipment</h3>${eqRows}</div><label class="full">Notes<textarea name="notes"></textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancel-modal">Cancel</button><button class="primary">Create Drop-off</button></div>`,saveDeployment);setTimeout(()=>$('cancel-modal').onclick=closeModal);}
  async function saveDeployment(fd){const v=Object.fromEntries(fd.entries()),job=s.jobs.find(j=>j.id===v.job_id),customer=Array.isArray(job?.customers)?job.customers[0]:job?.customers;const r=await client.from('equipment_deployments').insert({organization_id:s.orgId,job_id:v.job_id||null,customer_name:v.customer_name||customer?.name||job?.name||null,location:v.location||job?.property_address||null,pickup_due_at:v.pickup_due?new Date(v.pickup_due).toISOString():null,notes:v.notes||null,created_by:s.user.id}).select('id').single();if(r.error)return toast(r.error.message,'error');const items=s.equipment.map(e=>({deployment_id:r.data.id,equipment_type_id:e.id,quantity:Number(v[`eq_${e.id}`])||0})).filter(x=>x.quantity>0);if(items.length){const ir=await client.from('equipment_deployment_items').insert(items);if(ir.error)return toast(ir.error.message,'error');}closeModal();toast('Drop-off created.');refreshAll();}
  async function closeDeployment(id){const {error}=await client.from('equipment_deployments').update({status:'picked_up',picked_up_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,'error');toast('Equipment marked picked up.');refreshAll();}
  function subscribe(){s.channels.forEach(c=>client.removeChannel(c));s.channels=[];['jobs','lead_imports','equipment_types','equipment_deployments','equipment_deployment_items'].forEach(table=>{const c=client.channel(`tracker-${table}-${s.orgId}`).on('postgres_changes',{event:'*',schema:'public',table,filter:table==='equipment_deployment_items'?undefined:`organization_id=eq.${s.orgId}`},()=>refreshAll()).subscribe();s.channels.push(c);});}
  function setup(){statuses.forEach(x=>$('job-status-filter').insertAdjacentHTML('beforeend',`<option>${x}</option>`));$('login-form').onsubmit=async e=>{e.preventDefault();$('login-error').textContent='';const {error}=await client.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(error)$('login-error').textContent=error.message;};$('logout-button').onclick=()=>client.auth.signOut().then(()=>location.reload());$('refresh-button').onclick=refreshAll;$('organization-select').onchange=e=>{s.orgId=e.target.value;localStorage.setItem('roomflow_tracker_org',s.orgId);refreshAll();subscribe();};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-page').forEach(x=>x.classList.toggle('active',x.id===`${b.dataset.tab}-tab`));scheduleBoardRotation();});$('job-search').oninput=()=>renderJobs(true);$('job-status-filter').onchange=()=>renderJobs(true);$('board-previous').onclick=()=>showBoardPage(s.boardPage-1);$('board-next').onclick=()=>showBoardPage(s.boardPage+1);$('board-pause').onclick=()=>{s.boardPaused=!s.boardPaused;$('board-pause').textContent=s.boardPaused?'Resume rotation':'Pause rotation';$('board-pause').setAttribute('aria-pressed',String(s.boardPaused));scheduleBoardRotation();};$('add-job-button').onclick=()=>openJobModal();$('add-equipment-button').onclick=()=>openEquipmentModal();$('add-deployment-button').onclick=openDeploymentModal;$('modal-close').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal();};let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>renderJobs(),180);});document.addEventListener('visibilitychange',scheduleBoardRotation);const requested=new URLSearchParams(location.search).get('tab')||location.hash.replace('#','');if(requested){const tab=document.querySelector(`.tab[data-tab="${requested}"]`);if(tab)tab.click();}boot();}
  document.addEventListener('DOMContentLoaded',setup);
})();
